version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./initdb.d:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: hogehoge

  wordpress:
    depends_on:
      - db
    image: wordpress:4.6.1
    links:
      - db
    ports:
      - "8000:80"
    volumes:
      - "./mu-plugins/mailcatcher.php:/var/www/html/wp-content/mu-plugins/mailcatcher.php"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: hogehoge
      TZ: Asia/Tokyo

  mailcatcher:
    build: mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
